// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUAT1MD7vLVNf0oxP23K1BlNJzGN8khPM',
    appId: '1:440883441102:web:090f15505d8c91d1b94f9f',
    messagingSenderId: '440883441102',
    projectId: 'clone-61724',
    authDomain: 'clone-61724.firebaseapp.com',
    storageBucket: 'clone-61724.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgdGdBAFNNKueFMAbDzOkB87BbsQlvZdQ',
    appId: '1:440883441102:android:96db4e0d2ad78ceeb94f9f',
    messagingSenderId: '440883441102',
    projectId: 'clone-61724',
    storageBucket: 'clone-61724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn4rNjuzm5LRKnKVutyZmqonj5hOwTClA',
    appId: '1:440883441102:ios:c11dbe5594f05d92b94f9f',
    messagingSenderId: '440883441102',
    projectId: 'clone-61724',
    storageBucket: 'clone-61724.appspot.com',
    iosClientId: '440883441102-gsvgmsh0m0h7ibkshc6bu188f6s9uk9r.apps.googleusercontent.com',
    iosBundleId: 'lizwahome.app.amazonClone',
  );
}
